apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wordpresses.controller.hxstarrys.me
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only"
spec:
  # group
  group: controller.hxstarrys.me
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                serviceName:
                  type: string
                dbSecretName:
                  type: string
                dbSecretKey:
                  type: string
                dbVersion:
                  type: string
                wpVersion:
                  type: string
                dbPvcName:
                  type: string
                wpPvcName:
                  type: string
                wpPort:
                  type: integer
                  minimum: 1
                  maximum: 65535
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 1
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  names:
    kind: Wordpress
    plural: wordpresses
    shortNames:
      - wp
  scope: Namespaced