apiVersion: controller.hxstarrys.me/v1
kind: Wordpress
metadata:
  name: wordpress-example
spec:
  dbVersion: "5.7"  # mysql:<dbVersion>
  wpVersion: "4.8-apache" # wordpress:<wpVersion>
  dbSecretName: "mysql-passwd"
  dbSecretKey: "password"
  dbPvcName: "mysql-pvc"
  wpPvcName: "wordpress-pvc"
  deploymentName: wordpress-example
  serviceName: "wordpress-example-service"
  replicas: 1